
name: "Typescript Build/Push"
author: "Paul Gonzalez-Becerra"
description: "Builds the typescript project(s) and pushes any new items to make sure the repo always has a built project."
inputs:
  directories:
    description: "The list of directories to build the typescripts from, if omitted then it will use the base project directory."
    required: false
  user-name:
    description: "The name of a contributor of the repository, used for pushing to git."
    required: true
  user-email:
    description: "The email of a contributor of the repository, used for pushing to git."
    required: true
  message:
    description: "The commit message that will appear when a build has completed."
    required: true
    default: "Automatically built unbuilt typescript"
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  color: "blue"
  icon: "file-plus"
